namespace :data do
  desc 'Create experts'
  task create_experts: :environment do
    Expert.create!([
      { account: '姜明宝', name: '姜明宝', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '吴勇毅', name: '吴勇毅', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '丁安琪', name: '丁安琪', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '卢福波', name: '卢福波', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '刘骏', name: '刘骏', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '李泉', name: '李泉', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '吴中伟', name: '吴中伟', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '赵金铭', name: '赵金铭', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '张建民', name: '张建民', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '朱小健', name: '朱小健', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '阮福禄', name: '阮福禄', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '刘乐宁', name: '刘乐宁', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '刘富华', name: '刘富华', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '古川裕', name: '古川裕', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '白乐桑', name: '白乐桑', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '袁博平', name: '袁博平', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '施仲谋', name: '施仲谋', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '孟柱亿', name: '孟柱亿', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '崔希亮', name: '崔希亮', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '宁继鸣', name: '宁继鸣', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '杨金成', name: '杨金成', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '孟长勇', name: '孟长勇', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '张晓慧', name: '张晓慧', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '骆小所', name: '骆小所', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '李夏德', name: '李夏德', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '周敏康', name: '周敏康', password: '12th_isclt', password_confirmation: '12th_isclt', primary: true },
      { account: '安雄', name: '安雄', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '白建华', name: '白建华', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '陈曦', name: '陈曦', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '吴英成', name: '吴英成', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '谷丰', name: '谷丰', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '蔡昌杰', name: '蔡昌杰', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '朝吉勒玛', name: '朝吉勒玛', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '袁礼', name: '袁礼', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '钟英华', name: '钟英华', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '希夏姆', name: '希夏姆', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '顾安达', name: '顾安达', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '易福成', name: '易福成', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '柯佩琦', name: '柯佩琦', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '姚载瑜', name: '姚载瑜', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '马西尼', name: '马西尼', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '赵勇', name: '赵勇', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '李伟', name: '李伟', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '帅式毅', name: '帅式毅', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '杜可歆', name: '杜可歆', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '中川正之', name: '中川正之', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '陈秀慧', name: '陈秀慧', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '吴坚立', name: '吴坚立', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '黄端铭', name: '黄端铭', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '塔勒哈特·马木尔', name: '塔勒哈特·马木尔', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '黄小明', name: '黄小明', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '谢卫', name: '谢卫', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '郭红', name: '郭红', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '黄彬', name: '黄彬', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '王贵彬', name: '王贵彬', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '王京', name: '王京', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '周洪波', name: '周洪波', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false },
      { account: '沙宗元', name: '沙宗元', password: '12th_isclt', password_confirmation: '12th_isclt', primary: false }
    ])
  end
end